### ISSUE TITLE
怎么提交翻译贡献

### ISSUE THREAD

**Issue by JaveleyQAQ** [Leon406/BurpSuiteCN-Release#10]
0.0

**Comment by Leon406** [comment]
这个repo只是发布, 没有源代码
可以提供white.txt, 下个版本合并进项目

**Comment by JaveleyQAQ** [comment]
> 这个repo只是发布, 没有源代码 可以提供white.txt, 下个版本合并进项目

师傅能加个v吗，white？不是提供cn吗
另外logg++的帮助我怎么匹配不到，，
![image](https://github.com/Leon406/BurpSuiteCN-Release/assets/132129852/14af5ba9-d060-4a42-b77e-fba633fa86b4)

**Comment by JaveleyQAQ** [comment]
> 我搞错了 外置cn.txt 翻译生效了吗?
> 
> 有些还没有找到插入点, 无法翻译

外置? 我直接重新打包的jar包

**Comment by JaveleyQAQ** [comment]
我感觉是没有匹配到完整，可能他把所有窗口好几行的内容当作一句话贴入的，但是我只匹配到了一行,,,所以没生效，具体我还没尝试，目前打算先翻译一些插件

**Comment by Leon406** [comment]
翻译不建议合并到cn.txt

进行新版本支持读取外置 cn*.txt 格式所有的翻译, 如果有空的话重新整理下

https://leon.lanzoub.com/b0dap74ni 提取码：1kbw

**Comment by JaveleyQAQ** [comment]
> 翻译不建议合并到cn.txt
> 
> 进行新版本支持读取外置 cn*.txt 格式所有的翻译, 如果有空的话重新整理下
> 
> https://leon.lanzoub.com/b0dap74ni 提取码：1kbw

外置不生效, 控制台倒是读取到了规则数量

**Comment by Leon406** [comment]
> > 翻译不建议合并到cn.txt
> > 进行新版本支持读取外置 cn*.txt 格式所有的翻译, 如果有空的话重新整理下
> > [https://www.lanzoub.com/b0dap74ni](https://www.lanzoub.com/b0dap74ni?pwd=1kbw) 提取码：1kbw
> 
> 外置不生效, 控制台倒是读取到了规则数量
我的问题, 白名单和翻译的搞混了

已更新 v3.5.21
