### ISSUE TITLE
3.5.20版本白屏BUG

### ISSUE THREAD

**Issue by Datch666** [Leon406/BurpSuiteCN-Release#14]
3.5.20版本  勾选loader+汉化 run启动会导致burp白屏（首次激活不会 只有激活之后再次run） 需要关闭keygen才可以恢复

如下是log whitelist.txt文件信息
RTFM	
lblOnDiskErrorMessage	
lblExistingProjectErrorMessage	
lblDiskProjectWarning	
lblSpacer	
RTFM	
lblSpacer	
lblErrorMessage	
bConfigPanelExplanation1	
lblError	
RTFM	
lblFileErrorMessage	
lblCorruptDataDetected

**Comment by Datch666** [comment]
使用burp版本 2023.5.1

**Comment by Leon406** [comment]
2023.5.1测试未发现问题
window 11 jdk 17

**Comment by Datch666** [comment]
> 2023.5.1测试未发现问题 window 11 jdk 17
jdk17.0.7 win11
jdk17.0.5 win10
已录制复现bug录屏和log（虚拟机为Win11测试 最后为win10实测 ）
复现结果：win11不白屏但卡死 关闭keygen正常 win10白屏 关闭keygen正常
[bug.zip](https://github.com/Leon406/BurpSuiteCN-Release/files/11523577/bug.zip)

**Comment by Leon406** [comment]
这跟设备的性能相关

大概是设备内存 不够了

**Comment by Leon406** [comment]
keygen只是个壳程序, 代替手动配置执行命令行的参数 
你可以把Loader command命令行的参数复制出来 单独写个bat文件执行看看

**Comment by Datch666** [comment]
3.5.23版本已解决本问题

**Comment by Leon406** [comment]
> 3.5.23版本已解决本问题

那估计真是性能问题了, 每次翻译都需要遍历线程栈,导致耗时较长
