### ISSUE TITLE
关于"部分页面无法翻译"的问题

### ISSUE THREAD

**Issue by xcxmiku** [Leon406/BurpSuiteCN-Release#15]
可以基于该项目
https://github.com/ankokuty/Belle

**Comment by Leon406** [comment]
感谢反馈
看了下,代码基本类似, 把输入文本的过滤改成一样的, 没有看到新的有用的插入点

**Comment by xcxmiku** [comment]
但Belle确实是可以日化burp几乎所有页面的。

**Comment by Leon406** [comment]
设置的树状菜单无法翻译, 但是空白页面的信息可以翻译
