### ISSUE TITLE
Mac不生效 

### ISSUE THREAD

**Issue by JaveleyQAQ** [Leon406/BurpSuiteCN-Release#16]
首先是☑️勾选后不会自动添加burpsuitloader.jar=loader,hanizfy参数
![image](https://github.com/Leon406/BurpSuiteCN-Release/assets/132129852/52e397d5-8a6d-4f19-85b0-ec3968d48a35)

其次是参数生效后，破解不成功，我是直接使用vmoptions进行添加的，这个操作在win上是没问题的
![image](https://github.com/Leon406/BurpSuiteCN-Release/assets/132129852/cdf0024c-c998-4e1f-bf47-27a1129f6571)
![image](https://github.com/Leon406/BurpSuiteCN-Release/assets/132129852/a9f8cb27-1ff9-481b-aa11-40ea92a749b6)

**Comment by Leon406** [comment]
暂时的话,
翻译不启用loader看看
再用第三方 loader jar包看看能否使用, 可以加多个javaagent参数

可以试试坛友封装的版本
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1544866&highlight=burpsuit

方便的话提供以下信息, 分析的问题, 没有mac电脑, 下周公司看看
可以先提供bp版本或者下载链接 和 jdk信息(java -version)

**Comment by Leon406** [comment]
MacOS 的确有问题， 选项少参数
可以手动配置
用以下shell，jdk 17， loader可以正常使用， 参数不能少了，少了某些功能会失效

`java -XX:+IgnoreUnrecognizedVMOptions -javaagent:burpsuitloader-3.5.23-all.jar=loader,han --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -jar burpsuite_pro_v2023.7.jar`

**Comment by Leon406** [comment]
已修复mac OS启动器问题,可以下载最新版本
