### ISSUE TITLE
如何还原插件启动时界面

### ISSUE THREAD

**Issue by githubb000** [Leon406/BurpSuiteCN-Release#17]
师傅好！启动时勾选自动启动（auto start）后可以正常使用，但是如果我想还原到刚开始启动burpsuitloader-x.xx-all.jar时的界面需要如何操作。

**Comment by Leon406** [comment]
[keygen页面 (按需勾选loader,汉化,一键启动)
java -jar burpsuitloader-x.xx-all.jar -r](https://github.com/Leon406/BurpSuiteCN-Release#keygen页面-按需勾选loader汉化一键启动)
