### ISSUE TITLE
新版本burp部分汉化失效

### ISSUE THREAD

**Issue by Datch666** [Leon406/BurpSuiteCN-Release#18]
截图如下 jdk版本17.0.9 BurpSuite V2023.10.3.4
![(J4`JL8~0RMB(C`X6()SPNE](https://github.com/Leon406/BurpSuiteCN-Release/assets/61700483/f5a11841-afe8-46b3-9ae0-151588dcfa6c)
![JTLP`96 EEIB LQ8~JLMA~3](https://github.com/Leon406/BurpSuiteCN-Release/assets/61700483/c26dbf1a-d1c8-4b83-af7d-fd1d7f3957f0)
![W( 9 GIUF)D8L){ZVR)PKP2](https://github.com/Leon406/BurpSuiteCN-Release/assets/61700483/de4bd8ef-5cce-4135-b8fe-76630d7dcf7b)
![U{0SKYXZZU3K 9~FRL_ 1O5](https://github.com/Leon406/BurpSuiteCN-Release/assets/61700483/f58e4bcc-91a0-41af-a583-f00794755644)

**Comment by Datch666** [comment]
补充
![image](https://github.com/Leon406/BurpSuiteCN-Release/assets/61700483/894013bd-cb1f-413d-a079-503c86e42027)

**Comment by Datch666** [comment]
[unTranslate.txt](https://github.com/Leon406/BurpSuiteCN-Release/files/13327058/unTranslate.txt)

**Comment by Datch666** [comment]
[cn.txt](https://github.com/Leon406/BurpSuiteCN-Release/files/13327067/cn.txt)
贡献自己的翻译（有些位置添加翻译后并不生效，就删除了 等大佬翻译一下吧）

**Comment by Datch666** [comment]
贡献自己的翻译（有些位置添加翻译后并不生效，就删除了 等大佬翻译一下吧）
[cn.txt](https://github.com/Leon406/BurpSuiteCN-Release/files/13327077/cn.txt)

**Comment by Leon406** [comment]
树状菜单,目前因个人技术问题,无法翻译, 

其他的翻译,可以临时加外置文件,
最近比较慢, 后面抽空翻译下

**Comment by 2145425431232** [comment]
您好我想问一下，这几个文件是需要自己手动注入进去的吗

**Comment by Leon406** [comment]
> 您好我想问一下，这几个文件是需要自己手动注入进去的吗
放在根目录, 以cn开头的txt 就行
