### ISSUE TITLE
关闭注册机burp才可运行BUG

### ISSUE THREAD

**Issue by Datch666** [Leon406/BurpSuiteCN-Release#19]
激活burp后 Run后需要关闭注册机才可以运行，附录屏
[2023-11-11 21-35-49.zip](https://github.com/Leon406/BurpSuiteCN-Release/files/13325624/2023-11-11.21-35-49.zip)

**Comment by Datch666** [comment]
[unTranslate.txt](https://github.com/Leon406/BurpSuiteCN-Release/files/13326944/unTranslate.txt)

**Comment by Leon406** [comment]
这个的确有问题, 之前就有发现,目前不知道解决方案


默认勾选 auto start 不弹注册页没有问题
