### ISSUE TITLE
手动编辑命令前缀

### ISSUE THREAD

**Issue by Z-fly** [Leon406/BurpSuiteCN-Release#20]
![image](https://github.com/Leon406/BurpSuiteCN-Release/assets/10470892/bd5baa74-facf-4296-98b8-bca1f399a8f5)
当前装了JDK8和JDK21，默认JDK8，结果就无法启动了
希望能手动编辑命令前缀

**Comment by Leon406** [comment]
![image](https://github.com/Leon406/BurpSuiteCN-Release/assets/26186607/490d41d1-d0a7-4dd5-903a-a9f98879a06f)

只支持jdk11+, 新版bp也不支持低版本jdk了

可以在当前目录复制高版本 jre，或者直接使用第三方的整合版本

如果非要使用jdk8, 可以参考以下，自己编写命令

https://github.com/Leon406/BurpSuiteCN-Release?tab=readme-ov-file#java-agent%E9%85%8D%E7%BD%AE%E6%96%B9%E5%BC%8F%E5%A6%82%E6%9E%9C%E4%B8%80%E9%94%AE%E5%90%AF%E7%94%A8%E6%9C%89%E9%97%AE%E9%A2%98%E7%9A%84%E5%BB%BA%E8%AE%AE%E9%87%87%E7%94%A8%E8%BF%99%E7%A7%8D%E6%96%B9%E5%BC%8F

**Comment by Z-fly** [comment]
我的意思是，增加一个选项，是否使用绝对路径，我不是非要使用jdk8，而是环境变量当前是jdk8
我之后测一下绝对路径启动burpsuitloader

**Comment by Leon406** [comment]
默认会使用当前目录下 jre或bin目录的  java
如果没有，才会使用环境变量

**Comment by Datch666** [comment]
可以吧Loader Command启动的命令框放开 就可以自定义启动命令了 最好将配置文件写出来，优先按照配置文件的命令启动（还可以吧汉化 loader 自启动等内容也写进去了）

**Comment by Leon406** [comment]
[burpsuitloader-4.5.1-all.zip](https://github.com/Leon406/BurpSuiteCN-Release/files/15174032/burpsuitloader-4.5.1-all.zip)

加入两个环境变量
bp.java
bp.java.options

bp.java 可以配置自定义的java home 
bp.java.options  配置jvm参数，一般不需要配置

**Comment by Datch666** [comment]
> [burpsuitloader-4.5.1-all.zip](https://github.com/Leon406/BurpSuiteCN-Release/files/15174032/burpsuitloader-4.5.1-all.zip)
> 
> 加入两个环境变量 bp.java bp.java.options
> 
> bp.java 可以配置java home的自定义 bp.java.options 配置jvm参数，一般不需要配置

有个小问题，字符没有规范编码格式 导致乱码
![Uploading 1Y(DP40HU585VR%ZR(G0FIC.png…]()

**Comment by Datch666** [comment]
> > > [burpsuitloader-4.5.1-all.zip](https://github.com/Leon406/BurpSuiteCN-Release/files/15174032/burpsuitloader-4.5.1-all.zip)
> > > 加入两个环境变量 bp.java bp.java.options 
> > > bp.java 可以配置java home的自定义 bp.java.options 配置jvm参数，一般不需要配置
> > 
> > 
> > 有一个小问题，字符没有规范编码格式导致乱码![图像](https://private-user-images.githubusercontent.com/61700483/327719370-6eb0e0d0-43f0-400c-bc53-057cebada998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzM1MTYsIm5iZiI6MTcxNDczMzIxNiwicGF0aCI6Ii82MTcwMDQ4My8zMjc3MTkzNzAtNmViMGUwZDAtNDNmMC00MDBjLWJjNTMtMDU3Y2ViYWRhOTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDEwNDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MmZkMDBlNDA2ODlmYzYwZmNjY2M1YTMzYjVhNmJiYmFjYTAzYjE3MzZmNDM5NmQzMzNmOGY0OGM3Zjc1MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFBk0N1KTcqDGLoWZwFlJrCjWhEqPR-60dHJgp1WSuI)
> 
> cmd或bat命令加下 chcp 65001
> 
> 或者设置环境变量 bp.java.options -Dfile.encoding=utf-8

![image](https://github.com/user-attachments/assets/5ea3f542-9dee-43d9-b2fb-0c742a63dc49)
额 这就算是指定编码格式也没用哈哈
