### ISSUE TITLE
发现翻译的宝藏 建议分割单独的翻译jar

### ISSUE THREAD

**Issue by 1trapcode** [Leon406/BurpSuiteCN-Release#7]
嗯..
在windows11母鸡上，不定时随机性发生屏幕重绘或者闪退。
找了一波问题了，解决办法还是添加启动参数。
```-Dsun.java2d.d3d=false``` 
```-Dsun.java2d.noddraw=true```

但是keygen原参数无法添加上面2个参数
好像是 因为开头使用 ```-XX:+IgnoreUnrecognizedVMOptions```
通过shell可以成功添加参数

还有个建议
建议作者分割单独的翻译jar出来
哈哈 对java确实不熟悉
不然就能帮上忙了

**Comment by Leon406** [comment]
README已经更新, 建议使用javaagent方式,加入参数启用相关功能
